/**
 * GENERATED by apx-testgen from pages/p00110-customer-details.apx — DO NOT EDIT.
 * Typed accessor page object built on @apx/testkit primitives — no raw
 * selectors. Item accessors rest on the VERIFIED apex.item contract; button
 * methods use accessible-role/label locators (region/button DOM convention
 * still open — see docs/grammar-assumptions.md). Click methods pass their
 * button's semantic identity (pageId + .apx identifier) through to
 * buttonByLabel() so coverage tracking never collapses two different,
 * same-labeled buttons into one entry -- see @apx/testkit's coverage.ts.
 * Buttons whose label collides with another button's on this same page do
 * NOT get a generated click method at all -- see the comment in their
 * place below for why and what would resolve it.
 */
import type { Page } from '@playwright/test';
import { apexPageUrl, buttonByLabel, gotoApexPage } from '@apx/testkit';
import { APP_BASE } from '../playwright.config.js';

export class CustomerDetailsPage {
  static readonly alias = 'customer-details';

  constructor(private readonly page: Page) {}

  url(): string {
    return apexPageUrl(APP_BASE, CustomerDetailsPage.alias);
  }

  /** Navigate here and arm the console guard; returns any console/page errors seen. */
  async goto(): Promise<string[]> {
    return gotoApexPage(this.page, this.url());
  }

  /** "Delete" */
  async clickDeleteCustomer(): Promise<void> {
    await buttonByLabel(this.page, 'Delete', { pageId: 110, identifier: 'delete_customer' }).click();
  }

  /** "Create" */
  async clickCreateCustomer(): Promise<void> {
    await buttonByLabel(this.page, 'Create', { pageId: 110, identifier: 'create_customer' }).click();
  }
}
