/**
 * GENERATED by apx-testgen from pages/p00110-customer-details.apx — DO NOT EDIT.
 * Regenerate after any .apx change; review this file's diff alongside the .apx diff.
 * Assertions limited to runtime-verified contracts (V1-V6), implemented once in
 * @apx/testkit — see that package before touching any of the helpers used below.
 * Navigation and item access go through the generated page object
 * (./p00110-customer-details.page.js), not raw testkit calls, so both stay in sync.
 * Regions present in metadata: (none)
 * No interactiveReport/cards/facetedSearch regions on this page -- no region resolve-check to emit.
 */
import { expect, test } from '@playwright/test';
import { expectButtonsPresent, normalizeTitle } from '@apx/testkit';
import { CustomerDetailsPage } from './p00110-customer-details.page.js';

test.describe('page 110: Customer Details', () => {
  test('loads via alias URL with clean console' , async ({ page }) => {
    const po = new CustomerDetailsPage(page);
    const errors = await po.goto();
    await page.waitForTimeout(1000);
    expect(errors).toEqual([]);
  });

  test('title matches metadata (normalized)', async ({ page }) => {
    const po = new CustomerDetailsPage(page);
    await po.goto();
    expect(normalizeTitle(await page.title())).toBe(normalizeTitle('Customer Details'));
  });

  test('every labeled .apx button exists (2 buttons)', async ({ page }) => {
    const po = new CustomerDetailsPage(page);
    await po.goto();
    await expectButtonsPresent(page, ['Delete', 'Create']);
  });
});
