/**
 * GENERATED by apx-testgen from pages/p00003-employee.apx — DO NOT EDIT.
 * Typed accessor page object built on @apx/testkit primitives — no raw
 * selectors. Item accessors rest on the VERIFIED apex.item contract; button
 * methods use accessible-role/label locators (region/button DOM convention
 * still open — see docs/grammar-assumptions.md). Click methods pass their
 * button's semantic identity (pageId + .apx identifier) through to
 * clickButton() so coverage tracking never collapses two different,
 * same-labeled buttons into one entry -- see @apx/testkit's coverage.ts.
 * Buttons whose label collides with another button's on this same page do
 * NOT get a generated click method at all -- see the comment in their
 * place below for why and what would resolve it.
 */
import type { Page } from '@playwright/test';
import { ApexItem, apexPageUrl, clickButton, gotoApexPage } from '@apx/testkit';
import { APP_BASE } from '../playwright.config.js';

export class EmployeePage {
  static readonly alias = 'employee';

  constructor(private readonly page: Page) {}

  url(): string {
    return apexPageUrl(APP_BASE, EmployeePage.alias);
  }

  /** Navigate here and arm the console guard; returns any console/page errors seen. */
  async goto(): Promise<string[]> {
    return gotoApexPage(this.page, this.url());
  }

  /** hidden */
  get empno(): ApexItem {
    return new ApexItem(this.page, 'P3_EMPNO', 3);
  }

  /** textField, "Name", required */
  get ename(): ApexItem {
    return new ApexItem(this.page, 'P3_ENAME', 3);
  }

  /** "Save" */
  async clickSave(): Promise<void> {
    await clickButton(this.page, 'Save', { pageId: 3, identifier: 'save' });
  }
}
