/**
 * GENERATED by apx-testgen from pages/p00003-employee.apx — DO NOT EDIT.
 * Regenerate after any .apx change; review this file's diff alongside the .apx diff.
 * Assertions limited to runtime-verified contracts (V1-V6), implemented once in
 * @apx/testkit — see that package before touching any of the helpers used below.
 * Navigation and item access go through the generated page object
 * (./p00003-employee.page.js), not raw testkit calls, so both stay in sync.
 * Regions present in metadata: employee
 * No interactiveReport/cards/facetedSearch regions on this page -- no region resolve-check to emit.
 * Other region types NOT covered by an auto-generated assertion (no verified DOM convention -- see docs/grammar-assumptions.md "Still open"): employee (form).
 */
import { expect, test } from '@playwright/test';
import { expectItemsPresent, expectButtonsPresent, normalizeTitle } from '@apx/testkit';
import { EmployeePage } from './p00003-employee.page.js';

test.describe('page 3: Employee', () => {
  test('loads via alias URL with clean console' , async ({ page }) => {
    const po = new EmployeePage(page);
    const errors = await po.goto();
    await page.waitForTimeout(1000);
    expect(errors).toEqual([]);
  });

  test('title matches metadata (normalized)', async ({ page }) => {
    const po = new EmployeePage(page);
    await po.goto();
    expect(normalizeTitle(await page.title())).toBe(normalizeTitle('Employee'));
  });

  test('every .apx pageItem exists in DOM/apex.item registry (2 items, 1 hidden)', async ({ page }) => {
    const po = new EmployeePage(page);
    await po.goto();
    await expectItemsPresent(page, ['P3_EMPNO', 'P3_ENAME']);
  });

  test('apex.item round-trip on P3_ENAME', async ({ page }) => {
    const po = new EmployeePage(page);
    await po.goto();
    await po.ename.setValue('apx-testgen');
    expect(await po.ename.getValue()).toBe('apx-testgen');
  });

  test('every labeled .apx button exists (1 button)', async ({ page }) => {
    const po = new EmployeePage(page);
    await po.goto();
    await expectButtonsPresent(page, ['Save']);
  });
});
