/**
 * GENERATED by apx-testgen from pages/p00220-faceted-search-content-row.apx — DO NOT EDIT.
 * Regenerate after any .apx change; review this file's diff alongside the .apx diff.
 * Assertions limited to runtime-verified contracts (V1-V5). Regions present in
 * metadata: active-facets, button-bar, search, search-results
 * TODO(region-contract): emit region assertions once REGION DISCOVERY report
 * establishes the DOM convention for region static ids.
 */
import { expect, test, type Page } from '@playwright/test';
import { APP_BASE } from '../playwright.config.js';

const pageUrl = () => `${APP_BASE.replace(/\/+$/, '')}/faceted-search-content-row`;
const norm = (s: string) =>
  s.normalize('NFKC').replace(/[\u2010-\u2015\u2212]/g, '-').replace(/[\s\u00A0]+/g, ' ').trim();

function armConsoleGuard(page: Page): string[] {
  const errors: string[] = [];
  page.on('console', (m) => { if (m.type() === 'error') errors.push(`console.error: ${m.text()}`); });
  page.on('pageerror', (e) => errors.push(`pageerror: ${e.message}`));
  return errors;
}

async function gotoPage(page: Page): Promise<string[]> {
  const errors = armConsoleGuard(page);
  const resp = await page.goto(pageUrl(), { waitUntil: 'domcontentloaded' });
  expect(resp?.ok(), `GET ${pageUrl()} -> ${resp?.status()}`).toBe(true);
  await page.waitForFunction(() => typeof (window as any).apex?.item === 'function');
  return errors;
}

test.describe('page 220: Faceted Search – Content Row', () => {
  test('loads via alias URL with clean console' , async ({ page }) => {
    const errors = await gotoPage(page);
    await page.waitForTimeout(1000);
    expect(errors).toEqual([]);
  });

  test('title matches metadata (normalized)', async ({ page }) => {
    await gotoPage(page);
    expect(norm(await page.title())).toBe(norm('Faceted Search – Content Row'));
  });
});
