/**
 * GENERATED by apx-testgen from pages/p00220-faceted-search-content-row.apx — DO NOT EDIT.
 * Regenerate after any .apx change; review this file's diff alongside the .apx diff.
 * Assertions limited to runtime-verified contracts (V1-V5), implemented once in
 * @apx/testkit — see that package before touching any of the helpers used below.
 * Regions present in metadata: active-facets, button-bar, search, search-results
 * TODO(region-contract): emit region assertions once REGION DISCOVERY report
 * establishes the DOM convention for region static ids.
 */
import { expect, test } from '@playwright/test';
import { apexPageUrl, expectItemsPresent, gotoApexPage, itemRoundTrip, normalizeTitle } from '@apx/testkit';
import { APP_BASE } from '../playwright.config.js';

const pageUrl = () => apexPageUrl(APP_BASE, 'faceted-search-content-row');

test.describe('page 220: Faceted Search – Content Row', () => {
  test('loads via alias URL with clean console' , async ({ page }) => {
    const errors = await gotoApexPage(page, pageUrl());
    await page.waitForTimeout(1000);
    expect(errors).toEqual([]);
  });

  test('title matches metadata (normalized)', async ({ page }) => {
    await gotoApexPage(page, pageUrl());
    expect(normalizeTitle(await page.title())).toBe(normalizeTitle('Faceted Search – Content Row'));
  });
});
