/**
 * GENERATED by apx-testgen from pages/p00330-item-selection-with-details.apx — DO NOT EDIT.
 * Regenerate after any .apx change; review this file's diff alongside the .apx diff.
 * Assertions limited to runtime-verified contracts (V1-V5). Regions present in
 * metadata: activity, details, details-2, faceted-search, flex-container, item-header, item-summary-details, key-facts, list-selection, metric-cards, no-item-selected, related-information, summary-container
 * TODO(region-contract): emit region assertions once REGION DISCOVERY report
 * establishes the DOM convention for region static ids.
 */
import { expect, test, type Page } from '@playwright/test';
import { APP_BASE } from '../playwright.config.js';

const pageUrl = () => `${APP_BASE.replace(/\/+$/, '')}/item-selection-with-details`;
const norm = (s: string) =>
  s.normalize('NFKC').replace(/[\u2010-\u2015\u2212]/g, '-').replace(/[\s\u00A0]+/g, ' ').trim();

function armConsoleGuard(page: Page): string[] {
  const errors: string[] = [];
  page.on('console', (m) => { if (m.type() === 'error') errors.push(`console.error: ${m.text()}`); });
  page.on('pageerror', (e) => errors.push(`pageerror: ${e.message}`));
  return errors;
}

async function gotoPage(page: Page): Promise<string[]> {
  const errors = armConsoleGuard(page);
  const resp = await page.goto(pageUrl(), { waitUntil: 'domcontentloaded' });
  expect(resp?.ok(), `GET ${pageUrl()} -> ${resp?.status()}`).toBe(true);
  await page.waitForFunction(() => typeof (window as any).apex?.item === 'function');
  return errors;
}

test.describe('page 330: Item Selection with Details', () => {
  test('loads via alias URL with clean console' , async ({ page }) => {
    const errors = await gotoPage(page);
    await page.waitForTimeout(1000);
    expect(errors).toEqual([]);
  });

  test('title matches metadata (normalized)', async ({ page }) => {
    await gotoPage(page);
    expect(norm(await page.title())).toBe(norm('Item Selection with Details'));
  });

  test('every .apx pageItem exists in DOM/apex.item registry (2 items, 2 hidden)', async ({ page }) => {
    await gotoPage(page);
    const presence = await page.evaluate(
      (ids: readonly string[]) =>
        ids.map((id) => ({
          id,
          ok: !!document.getElementById(id) || !!(window as any).apex.item(id)?.node,
        })),
      ['P330_SELECTED_ITEM_ID', 'P330_SELECTED_ITEM_ID_UI'],
    );
    const missing = presence.filter((p) => !p.ok).map((p) => p.id);
    expect(missing, 'items declared in .apx but absent at runtime').toEqual([]);
  });
});
