/**
 * GENERATED by apx-testgen from pages/p00330-item-selection-with-details.apx — DO NOT EDIT.
 * Regenerate after any .apx change; review this file's diff alongside the .apx diff.
 * Assertions limited to runtime-verified contracts (V1-V5), implemented once in
 * @apx/testkit — see that package before touching any of the helpers used below.
 * Regions present in metadata: activity, details, details-2, faceted-search, flex-container, item-header, item-summary-details, key-facts, list-selection, metric-cards, no-item-selected, related-information, summary-container
 * TODO(region-contract): emit region assertions once REGION DISCOVERY report
 * establishes the DOM convention for region static ids.
 */
import { expect, test } from '@playwright/test';
import { apexPageUrl, expectItemsPresent, gotoApexPage, itemRoundTrip, normalizeTitle } from '@apx/testkit';
import { APP_BASE } from '../playwright.config.js';

const pageUrl = () => apexPageUrl(APP_BASE, 'item-selection-with-details');

test.describe('page 330: Item Selection with Details', () => {
  test('loads via alias URL with clean console' , async ({ page }) => {
    const errors = await gotoApexPage(page, pageUrl());
    await page.waitForTimeout(1000);
    expect(errors).toEqual([]);
  });

  test('title matches metadata (normalized)', async ({ page }) => {
    await gotoApexPage(page, pageUrl());
    expect(normalizeTitle(await page.title())).toBe(normalizeTitle('Item Selection with Details'));
  });

  test('every .apx pageItem exists in DOM/apex.item registry (2 items, 2 hidden)', async ({ page }) => {
    await gotoApexPage(page, pageUrl());
    await expectItemsPresent(page, ['P330_SELECTED_ITEM_ID', 'P330_SELECTED_ITEM_ID_UI']);
  });
});
