/**
 * GENERATED by apx-testgen from pages/p00320-item-detail-full.apx — DO NOT EDIT.
 * Regenerate after any .apx change; review this file's diff alongside the .apx diff.
 * Assertions limited to runtime-verified contracts (V1-V5), implemented once in
 * @apx/testkit — see that package before touching any of the helpers used below.
 * Regions present in metadata: activity-2, child-records, comments, details, details-2, files, flex-container, item-detail-tabs, item-header, item-summary-details, key-facts, metric-cards, people, related-information, side-actions, summary-container
 * TODO(region-contract): emit region assertions once REGION DISCOVERY report
 * establishes the DOM convention for region static ids.
 */
import { expect, test } from '@playwright/test';
import { apexPageUrl, expectItemsPresent, gotoApexPage, itemRoundTrip, normalizeTitle } from '@apx/testkit';
import { APP_BASE } from '../playwright.config.js';

const pageUrl = () => apexPageUrl(APP_BASE, 'item-detail-full');

test.describe('page 320: Item Detail – Full', () => {
  test('loads via alias URL with clean console' , async ({ page }) => {
    const errors = await gotoApexPage(page, pageUrl());
    await page.waitForTimeout(1000);
    expect(errors).toEqual([]);
  });

  test('title matches metadata (normalized)', async ({ page }) => {
    await gotoApexPage(page, pageUrl());
    expect(normalizeTitle(await page.title())).toBe(normalizeTitle('Item Detail – Full'));
  });

  test('every .apx pageItem exists in DOM/apex.item registry (1 items, 0 hidden)', async ({ page }) => {
    await gotoApexPage(page, pageUrl());
    await expectItemsPresent(page, ['P320_COMMENT_TEXT']);
  });

  test('apex.item round-trip on P320_COMMENT_TEXT', async ({ page }) => {
    await gotoApexPage(page, pageUrl());
    const v = await itemRoundTrip(page, 'P320_COMMENT_TEXT', 'apx-testgen');
    expect(v).toBe('apx-testgen');
  });
});
