/**
 * GENERATED by apx-testgen from pages/p00420-data-entry-drawer-form.apx — DO NOT EDIT.
 * Regenerate after any .apx change; review this file's diff alongside the .apx diff.
 * Assertions limited to runtime-verified contracts (V1-V5), implemented once in
 * @apx/testkit — see that package before touching any of the helpers used below.
 * Regions present in metadata: assignment, basic-information, buttons-container, form, organization
 * TODO(region-contract): emit region assertions once REGION DISCOVERY report
 * establishes the DOM convention for region static ids.
 */
import { expect, test } from '@playwright/test';
import { apexPageUrl, expectItemsPresent, gotoApexPage, itemRoundTrip, normalizeTitle } from '@apx/testkit';
import { APP_BASE } from '../playwright.config.js';

const pageUrl = () => apexPageUrl(APP_BASE, 'data-entry-drawer-form');

test.describe('page 420: Data Entry – Drawer Form', () => {
  test('loads via alias URL with clean console' , async ({ page }) => {
    const errors = await gotoApexPage(page, pageUrl());
    await page.waitForTimeout(1000);
    expect(errors).toEqual([]);
  });

  test('title matches metadata (normalized)', async ({ page }) => {
    await gotoApexPage(page, pageUrl());
    expect(normalizeTitle(await page.title())).toBe(normalizeTitle('Data Entry – Drawer Form'));
  });

  test('every .apx pageItem exists in DOM/apex.item registry (13 items, 1 hidden)', async ({ page }) => {
    await gotoApexPage(page, pageUrl());
    await expectItemsPresent(page, ['P420_DEPARTMENT', 'P420_EMAIL', 'P420_EMPLOYMENT_TYPE', 'P420_END_DATE', 'P420_ID', 'P420_JOB', 'P420_JOB_TITLE', 'P420_LOCATION', 'P420_MANAGER', 'P420_NAME', 'P420_PHONE', 'P420_SALARY', 'P420_START_DATE']);
  });

  test('apex.item round-trip on P420_EMAIL', async ({ page }) => {
    await gotoApexPage(page, pageUrl());
    const v = await itemRoundTrip(page, 'P420_EMAIL', 'apx-testgen');
    expect(v).toBe('apx-testgen');
  });
});
