/**
 * GENERATED by apx-testgen from pages/p00420-data-entry-drawer-form.apx — DO NOT EDIT.
 * Regenerate after any .apx change; review this file's diff alongside the .apx diff.
 * Assertions limited to runtime-verified contracts (V1-V5). Regions present in
 * metadata: assignment, basic-information, buttons-container, form, organization
 * TODO(region-contract): emit region assertions once REGION DISCOVERY report
 * establishes the DOM convention for region static ids.
 */
import { expect, test, type Page } from '@playwright/test';
import { APP_BASE } from '../playwright.config.js';

const pageUrl = () => `${APP_BASE.replace(/\/+$/, '')}/data-entry-drawer-form`;
const norm = (s: string) =>
  s.normalize('NFKC').replace(/[\u2010-\u2015\u2212]/g, '-').replace(/[\s\u00A0]+/g, ' ').trim();

function armConsoleGuard(page: Page): string[] {
  const errors: string[] = [];
  page.on('console', (m) => { if (m.type() === 'error') errors.push(`console.error: ${m.text()}`); });
  page.on('pageerror', (e) => errors.push(`pageerror: ${e.message}`));
  return errors;
}

async function gotoPage(page: Page): Promise<string[]> {
  const errors = armConsoleGuard(page);
  const resp = await page.goto(pageUrl(), { waitUntil: 'domcontentloaded' });
  expect(resp?.ok(), `GET ${pageUrl()} -> ${resp?.status()}`).toBe(true);
  await page.waitForFunction(() => typeof (window as any).apex?.item === 'function');
  return errors;
}

test.describe('page 420: Data Entry – Drawer Form', () => {
  test('loads via alias URL with clean console' , async ({ page }) => {
    const errors = await gotoPage(page);
    await page.waitForTimeout(1000);
    expect(errors).toEqual([]);
  });

  test('title matches metadata (normalized)', async ({ page }) => {
    await gotoPage(page);
    expect(norm(await page.title())).toBe(norm('Data Entry – Drawer Form'));
  });

  test('every .apx pageItem exists in DOM/apex.item registry (13 items, 1 hidden)', async ({ page }) => {
    await gotoPage(page);
    const presence = await page.evaluate(
      (ids: readonly string[]) =>
        ids.map((id) => ({
          id,
          ok: !!document.getElementById(id) || !!(window as any).apex.item(id)?.node,
        })),
      ['P420_DEPARTMENT', 'P420_EMAIL', 'P420_EMPLOYMENT_TYPE', 'P420_END_DATE', 'P420_ID', 'P420_JOB', 'P420_JOB_TITLE', 'P420_LOCATION', 'P420_MANAGER', 'P420_NAME', 'P420_PHONE', 'P420_SALARY', 'P420_START_DATE'],
    );
    const missing = presence.filter((p) => !p.ok).map((p) => p.id);
    expect(missing, 'items declared in .apx but absent at runtime').toEqual([]);
  });

  test('apex.item round-trip on P420_EMAIL', async ({ page }) => {
    await gotoPage(page);
    const v = await page.evaluate(() => {
      const it = (window as any).apex.item('P420_EMAIL');
      it.setValue('apx-testgen');
      return it.getValue();
    });
    expect(v).toBe('apx-testgen');
  });
});
