/**
 * GENERATED by apx-testgen from pages/p00410-data-entry-simple-form.apx — DO NOT EDIT.
 * Regenerate after any .apx change; review this file's diff alongside the .apx diff.
 * Assertions limited to runtime-verified contracts (V1-V5), implemented once in
 * @apx/testkit — see that package before touching any of the helpers used below.
 * Regions present in metadata: basic-fields-container, buttons-container_1, data-entry-simple-form, form, organization
 * TODO(region-contract): emit region assertions once REGION DISCOVERY report
 * establishes the DOM convention for region static ids.
 */
import { expect, test } from '@playwright/test';
import { apexPageUrl, expectItemsPresent, gotoApexPage, itemRoundTrip, normalizeTitle } from '@apx/testkit';
import { APP_BASE } from '../playwright.config.js';

const pageUrl = () => apexPageUrl(APP_BASE, 'data-entry-simple-form');

test.describe('page 410: Data Entry – Simple Form', () => {
  test('loads via alias URL with clean console' , async ({ page }) => {
    const errors = await gotoApexPage(page, pageUrl());
    await page.waitForTimeout(1000);
    expect(errors).toEqual([]);
  });

  test('title matches metadata (normalized)', async ({ page }) => {
    await gotoApexPage(page, pageUrl());
    expect(normalizeTitle(await page.title())).toBe(normalizeTitle('Data Entry – Simple Form'));
  });

  test('every .apx pageItem exists in DOM/apex.item registry (9 items, 1 hidden)', async ({ page }) => {
    await gotoApexPage(page, pageUrl());
    await expectItemsPresent(page, ['P410_EMAIL', 'P410_FIELD_HELP', 'P410_ID', 'P410_INLINE_HELP', 'P410_JOB', 'P410_NAME', 'P410_NOTES', 'P410_SALARY', 'P410_START_DATE']);
  });

  test('apex.item round-trip on P410_EMAIL', async ({ page }) => {
    await gotoApexPage(page, pageUrl());
    const v = await itemRoundTrip(page, 'P410_EMAIL', 'apx-testgen');
    expect(v).toBe('apx-testgen');
  });
});
