/**
 * GENERATED by apx-testgen from pages/p00050-projects.apx — DO NOT EDIT.
 * Regenerate after any .apx change; review this file's diff alongside the .apx diff.
 * Assertions limited to runtime-verified contracts (V1-V6), implemented once in
 * @apx/testkit — see that package before touching any of the helpers used below.
 * Navigation and item access go through the generated page object
 * (./p00050-projects.page.js), not raw testkit calls, so both stay in sync.
 * Regions present in metadata: projects, archived-projects
 * Region resolve-check emitted for 2 interactiveReport/cards/facetedSearch region(s) below -- resolved LIVE via resolveRegion() (ADR-003: htmlDomId tried first when set, then the export identifier), never a static id baked in at generation time.
 */
import { expect, test } from '@playwright/test';
import { resolveRegion, normalizeTitle } from '@apx/testkit';
import { ProjectsPage } from './p00050-projects.page.js';

test.describe('page 50: Projects', () => {
  test('loads via alias URL with clean console' , async ({ page }) => {
    const po = new ProjectsPage(page);
    const errors = await po.goto();
    await page.waitForTimeout(1000);
    expect(errors).toEqual([]);
  });

  test('title matches metadata (normalized)', async ({ page }) => {
    const po = new ProjectsPage(page);
    await po.goto();
    expect(normalizeTitle(await page.title())).toBe(normalizeTitle('Projects'));
  });

  test('every interactiveReport/cards/facetedSearch region resolves (2 regions)', async ({ page }) => {
    const po = new ProjectsPage(page);
    await po.goto();
    // ADR-003 layered resolution, confirmed LIVE per region (htmlDomId
    // tried first when set, then the export identifier) -- resolveRegion()
    // hard-fails with a specific message if neither candidate resolves,
    // rather than silently trusting a static guess.
    const regionCandidateSets = [
      { identifier: 'projects', candidates: [{ value: 'projects_report', strategy: 'htmlDomId' as const }, { value: 'projects', strategy: 'export-identifier' as const }] },
      { identifier: 'archived-projects', candidates: [{ value: 'archived-projects', strategy: 'export-identifier' as const }] }
    ];
    for (const { identifier, candidates } of regionCandidateSets) {
      await resolveRegion(page, candidates, { pageId: 50, identifier });
    }
  });
});
