/**
 * GENERATED by apx-testgen from pages/p00010-registration.apx — DO NOT EDIT.
 * Regenerate after any .apx change; review this file's diff alongside the .apx diff.
 * Assertions limited to runtime-verified contracts (V1-V6), implemented once in
 * @apx/testkit — see that package before touching any of the helpers used below.
 * Navigation and item access go through the generated page object
 * (./p00010-registration.page.js), not raw testkit calls, so both stay in sync.
 * Regions present in metadata: registration-form
 * No interactiveReport/cards/facetedSearch regions on this page -- no region resolve-check to emit.
 * Other region types NOT covered by an auto-generated assertion (no verified DOM convention -- see docs/grammar-assumptions.md "Still open"): registration-form (form).
 */
import { expect, test } from '@playwright/test';
import { expectItemsPresent, expectButtonsPresent, normalizeTitle } from '@apx/testkit';
import { RegistrationPage } from './p00010-registration.page.js';

test.describe('page 10: Registration', () => {
  test('loads via alias URL with clean console' , async ({ page }) => {
    const po = new RegistrationPage(page);
    const errors = await po.goto();
    await page.waitForTimeout(1000);
    expect(errors).toEqual([]);
  });

  test('title matches metadata (normalized)', async ({ page }) => {
    const po = new RegistrationPage(page);
    await po.goto();
    expect(normalizeTitle(await page.title())).toBe(normalizeTitle('Registration | Customer Portal'));
  });

  test('every .apx pageItem exists in DOM/apex.item registry (3 items, 1 hidden)', async ({ page }) => {
    const po = new RegistrationPage(page);
    await po.goto();
    await expectItemsPresent(page, ['P10_CUSTOMER_ID', 'P10_FIRST_NAME', 'P10_EMAIL'], 10);
  });

  test('apex.item round-trip on P10_FIRST_NAME', async ({ page }) => {
    const po = new RegistrationPage(page);
    await po.goto();
    await po.firstName.setValue('apx-testgen');
    expect(await po.firstName.getValue()).toBe('apx-testgen');
  });

  test('every uniquely labeled .apx button exists (2 buttons)', async ({ page }) => {
    const po = new RegistrationPage(page);
    await po.goto();
    await expectButtonsPresent(page, ['Submit', 'Reset'], [{ pageId: 10, identifier: 'submit_registration' }, { pageId: 10, identifier: 'reset_form' }]);
  });
});
