/**
 * GENERATED by apx-testgen from pages/p00040-dashboard.apx — DO NOT EDIT.
 * Regenerate after any .apx change; review this file's diff alongside the .apx diff.
 * Assertions limited to runtime-verified contracts (V1-V6), implemented once in
 * @apx/testkit — see that package before touching any of the helpers used below.
 * Navigation and item access go through the generated page object
 * (./p00040-dashboard.page.js), not raw testkit calls, so both stay in sync.
 * Regions present in metadata: dashboard-cards
 * No interactiveReport/cards/facetedSearch regions on this page -- no region resolve-check to emit.
 * Other region types NOT covered by an auto-generated assertion (no verified DOM convention -- see docs/grammar-assumptions.md "Still open"): dashboard-cards (staticContent).
 */
import { expect, test } from '@playwright/test';
import { expectButtonsPresent, normalizeTitle } from '@apx/testkit';
import { DashboardPage } from './p00040-dashboard.page.js';

test.describe('page 40: Dashboard', () => {
  test('loads via alias URL with clean console' , async ({ page }) => {
    const po = new DashboardPage(page);
    const errors = await po.goto();
    await page.waitForTimeout(1000);
    expect(errors).toEqual([]);
  });

  test('title matches metadata (normalized)', async ({ page }) => {
    const po = new DashboardPage(page);
    await po.goto();
    expect(normalizeTitle(await page.title())).toBe(normalizeTitle('Dashboard'));
  });

  test('every labeled .apx button exists (4 buttons)', async ({ page }) => {
    const po = new DashboardPage(page);
    await po.goto();
    await expectButtonsPresent(page, ['Refresh', 'View Details', 'View Details', 'View Details']);
  });
});
