/**
 * GENERATED by apx-testgen from pages/p00040-dashboard.apx — DO NOT EDIT.
 * Typed accessor page object built on @apx/testkit primitives — no raw
 * selectors. Item accessors rest on the VERIFIED apex.item contract; button
 * methods use accessible-role/label locators (region/button DOM convention
 * still open — see docs/grammar-assumptions.md). Click methods pass their
 * button's semantic identity (pageId + .apx identifier) through to
 * buttonByLabel() so coverage tracking never collapses two different,
 * same-labeled buttons into one entry -- see @apx/testkit's coverage.ts.
 * Buttons whose label collides with another button's on this same page do
 * NOT get a generated click method at all -- see the comment in their
 * place below for why and what would resolve it.
 */
import type { Page } from '@playwright/test';
import { apexPageUrl, buttonByLabel, gotoApexPage } from '@apx/testkit';
import { APP_BASE } from '../playwright.config.js';

export class DashboardPage {
  static readonly alias = 'dashboard';

  constructor(private readonly page: Page) {}

  url(): string {
    return apexPageUrl(APP_BASE, DashboardPage.alias);
  }

  /** Navigate here and arm the console guard; returns any console/page errors seen. */
  async goto(): Promise<string[]> {
    return gotoApexPage(this.page, this.url());
  }

  /** "Refresh" */
  async clickRefreshDashboard(): Promise<void> {
    await buttonByLabel(this.page, 'Refresh', { pageId: 40, identifier: 'refresh_dashboard' }).click();
  }

  // Cannot generate a deterministic click method for 'view_details_card_1' ("View Details") --
  // its label is shared with 'view_details_card_2', 'view_details_card_3' on this same page, and buttonByLabel()'s
  // locator (page.getByRole('button', { name: 'View Details', exact: true })) cannot tell them apart. No advanced { htmlDomId } is set on this button, so there is currently no way to disambiguate it from a generated test alone.

  // Cannot generate a deterministic click method for 'view_details_card_2' ("View Details") --
  // its label is shared with 'view_details_card_1', 'view_details_card_3' on this same page, and buttonByLabel()'s
  // locator (page.getByRole('button', { name: 'View Details', exact: true })) cannot tell them apart. No advanced { htmlDomId } is set on this button, so there is currently no way to disambiguate it from a generated test alone.

  // Cannot generate a deterministic click method for 'view_details_card_3' ("View Details") --
  // its label is shared with 'view_details_card_1', 'view_details_card_2' on this same page, and buttonByLabel()'s
  // locator (page.getByRole('button', { name: 'View Details', exact: true })) cannot tell them apart. No advanced { htmlDomId } is set on this button, so there is currently no way to disambiguate it from a generated test alone.
}
