/**
 * GENERATED by apx-testgen from pages/p00100-edit.apx — DO NOT EDIT.
 * Regenerate after any .apx change; review this file's diff alongside the .apx diff.
 * Assertions limited to runtime-verified contracts (V1-V6), implemented once in
 * @apx/testkit — see that package before touching any of the helpers used below.
 * Navigation and item access go through the generated page object
 * (./p00100-edit.page.js), not raw testkit calls, so both stay in sync.
 * Regions present in metadata: (none)
 * No interactiveReport/cards/facetedSearch regions on this page -- no region resolve-check to emit.
 */
import { expect, test } from '@playwright/test';
import { expectItemsPresent, normalizeTitle } from '@apx/testkit';
import { EditPage } from './p00100-edit.page.js';

test.describe('page 100: Edit', () => {
  test('loads via alias URL with clean console' , async ({ page }) => {
    const po = new EditPage(page);
    const errors = await po.goto();
    await page.waitForTimeout(1000);
    expect(errors).toEqual([]);
  });

  test('title matches metadata (normalized)', async ({ page }) => {
    const po = new EditPage(page);
    await po.goto();
    expect(normalizeTitle(await page.title())).toBe(normalizeTitle('Edit'));
  });

  test('every .apx pageItem exists in DOM/apex.item registry (2 items, 0 hidden)', async ({ page }) => {
    const po = new EditPage(page);
    await po.goto();
    await expectItemsPresent(page, ['P100_JOB', 'P100_COMM']);
  });
});
