/**
 * GENERATED by apx-testgen from pages/p00080-sales-chart.apx — DO NOT EDIT.
 * Typed accessor page object built on @apx/testkit primitives — no raw
 * selectors. Item accessors rest on the VERIFIED apex.item contract; button
 * methods use accessible-role/label locators (region/button DOM convention
 * still open — see docs/grammar-assumptions.md). Click methods pass their
 * button's semantic identity (pageId + .apx identifier) through to
 * clickButton() so coverage tracking never collapses two different,
 * same-labeled buttons into one entry -- see @apx/testkit's coverage.ts.
 * Buttons whose label collides with another button's on this same page do
 * NOT get a generated click method at all -- see the comment in their
 * place below for why and what would resolve it.
 */
import type { Page } from '@playwright/test';
import { apexPageUrl, assessNavigationSafety, gotoApexPageAuto } from '@apx/testkit';
import { APP_BASE } from '../playwright.config.js';

export class SalesChartPage {
  static readonly alias = 'sales-chart';

  constructor(private readonly page: Page) {}

  url(): string {
    return apexPageUrl(APP_BASE, SalesChartPage.alias, true);
  }

  /** Navigate only when the page's declared security/mode permits a direct URL. */
  async goto(): Promise<string[]> {
    return gotoApexPageAuto(
      this.page,
      this.url(),
      assessNavigationSafety({ pageAccessProtection: 'unrestricted', isPublic: true }),
    );
  }


}
