/**
 * GENERATED by apx-testgen from pages/p00080-sales-chart.apx — DO NOT EDIT.
 * Regenerate after any .apx change; review this file's diff alongside the .apx diff.
 * Assertions limited to runtime-verified contracts (V1-V6), implemented once in
 * @apx/testkit — see that package before touching any of the helpers used below.
 * Navigation and item access go through the generated page object
 * (./p00080-sales-chart.page.js), not raw testkit calls, so both stay in sync.
 * Regions present in metadata: sales-by-region, sales-by-quarter
 * No interactiveReport/cards/facetedSearch regions on this page -- no region resolve-check to emit.
 * Chart type-check emitted for 1 region(s) with a known runtime id (htmlDomId set), resolved live via resolveRegion() before use.
 * 1 chart region(s) SKIPPED -- no htmlDomId set, runtime id genuinely unconstructible from static data (ADR-003 layer 3): sales-by-quarter.
 */
import { expect, test } from '@playwright/test';
import { resolveRegion, ApexChartRegion, normalizeTitle } from '@apx/testkit';
import { SalesChartPage } from './p00080-sales-chart.page.js';

test.describe('page 80: Sales Chart', () => {
  test('loads via alias URL with clean console' , async ({ page }) => {
    const po = new SalesChartPage(page);
    const errors = await po.goto();
    await page.waitForTimeout(1000);
    expect(errors).toEqual([]);
  });

  test('title matches metadata (normalized)', async ({ page }) => {
    const po = new SalesChartPage(page);
    await po.goto();
    expect(normalizeTitle(await page.title())).toBe(normalizeTitle('Sales Chart'));
  });

  test('every Chart region with a known runtime id resolves a real chart type (1 region)', async ({ page }) => {
    const po = new SalesChartPage(page);
    await po.goto();
    // declaredType is the region's chartSettings.type and is NOT asserted
    // for equality against the live type (confirmed NOT always the same,
    // e.g. declared "donut" reports live "pie" -- see
    // docs/quirks/26.1.json). Kept here for context only.
    const charts = [
      { identifier: 'sales-by-region', candidates: [{ value: 'salesPie1', strategy: 'htmlDomId' as const }], declaredType: 'pie' }
    ];
    for (const { identifier, candidates } of charts) {
      // ADR-003: htmlDomId is the ONLY evidence-backed candidate for
      // Chart -- the export identifier is confirmed NOT to work as a
      // fallback for this component type. resolveRegion() still confirms
      // it live rather than trusting the static field.
      const { runtimeId } = await resolveRegion(page, candidates, { pageId: 80, identifier });
      // JET chart widgets attach ojChart asynchronously -- wait for the
      // actual precondition (see ApexChartRegion's module doc) rather
      // than a fixed delay.
      await page.waitForFunction((regionId) => {
        const region = (window as any).apex?.region?.(regionId);
        return typeof region?.widget?.()?.ojChart === 'function';
      }, runtimeId);
      const chart = new ApexChartRegion(page, runtimeId, { pageId: 80, identifier });
      const liveType = await chart.getOption('type');
      expect(typeof liveType).toBe('string');
      expect(liveType).not.toBe('');
    }
  });
});
