import { cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { applyRegeneration, previewRegeneration } from '../src/regenerate.js';

let root: string;
let input: string;
let output: string;
const spec = 'p00003-employee.spec.ts';
const po = 'p00003-employee.page.ts';
const manifest = '.apx-testgen-manifest.json';
beforeEach(() => {
  root = mkdtempSync(join(tmpdir(), 'apx-regen-test-'));
  input = join(root, 'export'); output = join(root, 'output');
  cpSync(join(__dirname, 'fixtures/reference-fixtures'), input, { recursive: true });
});
afterEach(() => rmSync(root, { recursive: true, force: true }));
function apply() { return applyRegeneration(input, output, previewRegeneration(input, output).planHash); }
function renamePage() {
  const path = join(input, 'pages/p00003-employee.apx');
  writeFileSync(path, readFileSync(path, 'utf8').replace('alias: EMPLOYEE', 'alias: STAFF'));
}
describe('safe regeneration', () => {
  it('previews without creating the destination', () => {
    const plan = previewRegeneration(input, output);
    expect(plan.changes.map(change => change.action)).toEqual(['create', 'create']);
    expect(existsSync(output)).toBe(false);
    expect(previewRegeneration(input, output)).toEqual(plan);
  });
  it('creates owned output, then performs a byte-identical no-op', () => {
    apply();
    const bytes = readFileSync(join(output, manifest));
    expect(Object.keys(JSON.parse(bytes.toString()).files)).toEqual([po, spec]);
    const result = apply();
    expect(result.plan.changes.every(change => change.action === 'unchanged')).toBe(true);
    expect(result.backupDir).toBeNull();
    expect(readFileSync(join(output, manifest))).toEqual(bytes);
  });
  it('preserves unrelated custom files and directories', () => {
    mkdirSync(output); mkdirSync(join(output, 'custom'));
    writeFileSync(join(output, 'custom', 'workflow.spec.ts'), 'custom');
    writeFileSync(join(output, 'p99999-custom.spec.ts'), '// GENERATED by apx-testgen\ncustom');
    apply();
    expect(readFileSync(join(output, 'custom', 'workflow.spec.ts'), 'utf8')).toBe('custom');
    expect(readFileSync(join(output, 'p99999-custom.spec.ts'), 'utf8')).toContain('custom');
  });
  it('blocks unowned collisions, even when bytes would be identical', () => {
    apply(); rmSync(join(output, manifest));
    const plan = previewRegeneration(input, output);
    expect(plan.conflicts).toEqual([po, spec]);
    expect(() => applyRegeneration(input, output, plan.planHash)).toThrow(/conflicts/);
  });
  it('blocks manual edits without modifying any files', () => {
    apply(); writeFileSync(join(output, spec), 'manual edits');
    const before = readFileSync(join(output, po));
    expect(previewRegeneration(input, output).conflicts).toEqual([spec]);
    expect(() => apply()).toThrow(/conflicts/);
    expect(readFileSync(join(output, spec), 'utf8')).toBe('manual edits');
    expect(readFileSync(join(output, po))).toEqual(before);
  });
  it('blocks manually deleted owned files', () => {
    apply(); rmSync(join(output, spec));
    expect(previewRegeneration(input, output).conflicts).toEqual([spec]);
    expect(() => apply()).toThrow(/conflicts/);
  });
  it('backs up retired files after alias changes', () => {
    apply(); const oldBytes = readFileSync(join(output, spec)); renamePage();
    const result = apply();
    expect(result.backupDir).not.toBeNull();
    expect(readFileSync(join(result.backupDir!, spec))).toEqual(oldBytes);
    expect(existsSync(join(result.backupDir!, manifest))).toBe(true);
    expect(existsSync(join(output, spec))).toBe(false);
    expect(existsSync(join(output, 'p00003-staff.spec.ts'))).toBe(true);
  });
  it('does not retire an edited generated file', () => {
    apply(); writeFileSync(join(output, spec), 'custom edits'); renamePage();
    expect(() => apply()).toThrow(/conflicts/);
    expect(readFileSync(join(output, spec), 'utf8')).toBe('custom edits');
  });
  it('backs up replaced content', () => {
    apply(); const oldBytes = readFileSync(join(output, spec));
    const path = join(input, 'pages/p00003-employee.apx');
    writeFileSync(path, readFileSync(path, 'utf8').replace('title: Employee', 'title: Changed'));
    const result = apply();
    expect(readFileSync(join(result.backupDir!, spec))).toEqual(oldBytes);
    expect(readFileSync(join(output, spec))).not.toEqual(oldBytes);
  });
  it('rejects stale previews when generated content changes', () => {
    const plan = previewRegeneration(input, output); renamePage();
    expect(() => applyRegeneration(input, output, plan.planHash)).toThrow(/plan changed/);
    expect(existsSync(output)).toBe(false);
  });
  it('rejects stale previews when output changes', () => {
    apply(); const plan = previewRegeneration(input, output);
    writeFileSync(join(output, spec), 'manual');
    expect(() => applyRegeneration(input, output, plan.planHash)).toThrow(/plan changed/);
  });
  it('respects a preexisting writer lock', () => {
    mkdirSync(output); writeFileSync(join(output, '.apx-testgen.lock'), 'other writer');
    expect(() => apply()).toThrow();
    expect(readFileSync(join(output, '.apx-testgen.lock'), 'utf8')).toBe('other writer');
    expect(existsSync(join(output, spec))).toBe(false);
  });
  it.each([manifest, spec])('rejects symlink target %s without touching the referent', file => {
    mkdirSync(output); const outside = join(root, 'outside'); writeFileSync(outside, 'unchanged');
    symlinkSync(outside, join(output, file));
    expect(() => previewRegeneration(input, output)).toThrow(/non-regular/);
    expect(readFileSync(outside, 'utf8')).toBe('unchanged');
  });
  it('rejects an output directory symlink', () => {
    symlinkSync(input, output);
    expect(() => previewRegeneration(input, output)).toThrow(/non-symlink/);
  });
  it('rejects a backup directory symlink before moving files', () => {
    apply(); rmSync(join(output, '.apx-testgen-backups'), { recursive: true });
    symlinkSync(input, join(output, '.apx-testgen-backups')); renamePage();
    expect(() => apply()).toThrow(/non-symlink/);
    expect(existsSync(join(output, spec))).toBe(true);
    expect(existsSync(join(output, manifest))).toBe(true);
  });
  it.each([
    '{"version":2,"files":{}}',
    '{"version":1,"files":{"../escape":"abc"}}',
    '{"version":1,"files":[]}',
    'not json',
  ])('rejects corrupt ownership manifests: %s', content => {
    mkdirSync(output); writeFileSync(join(output, manifest), content);
    expect(() => apply()).toThrow();
    expect(readdirSync(output)).toEqual([manifest]);
  });
  it('invalid export does not create output', () => {
    rmSync(join(input, '.apex/apexlang.json'));
    expect(() => previewRegeneration(input, output)).toThrow();
    expect(existsSync(output)).toBe(false);
  });
  it('CLI previews and applies the exact plan', () => {
    const cli = join(__dirname, '../dist/regenerate-cli.js');
    const preview = spawnSync(process.execPath, [cli, input, '--out', output], { encoding: 'utf8' });
    expect(preview.status).toBe(0); expect(existsSync(output)).toBe(false);
    const result = spawnSync(process.execPath, [cli, input, '--out', output, '--apply', JSON.parse(preview.stdout).planHash], { encoding: 'utf8' });
    expect(result.status).toBe(0); expect(existsSync(join(output, manifest))).toBe(true);
  });
  it('CLI rejects a bare apply flag', () => {
    const result = spawnSync(process.execPath, [join(__dirname, '../dist/regenerate-cli.js'), input, '--out', output, '--apply'], { encoding: 'utf8' });
    expect(result.status).toBe(2); expect(existsSync(output)).toBe(false);
  });
});
