/**
 * apx-testgen — deterministic Playwright page-object + smoke-spec generator
 * for APEX 26.1+.
 *
 * Usage:  apx-testgen <export-dir> --out <tests-dir>
 * (base URL is read by the generated code from the consuming project's own
 * playwright.config.ts — APP_BASE export — not a generator flag; see
 * spike/playwright.config.ts for the convention generated imports assume.)
 *
 * Emits ONLY assertions whose metadata->DOM contract has been VERIFIED on a
 * live 26.1 instance (see docs/grammar-assumptions.md "Runtime verification"):
 *   V1 friendly URL = lowercased page alias        (verified)
 *   V2 pageItem id -> DOM node id, verbatim        (verified)
 *   V3 apex.item(id) round-trip                    (verified)
 *   V4 title equality ONLY after NFKC+dash/space normalization (verified rule)
 *   V5 console-error guard                          (verified)
 * Region and button assertions are emitted as TODO comments until the
 * REGION/BUTTON DISCOVERY reports establish their DOM convention.
 * V1-V5 are implemented once in @apx/testkit and imported by generated
 * code (never duplicated) — see packages/testkit for the primitives.
 *
 * Two files per page: a `.page.ts` PageObject (typed item accessors, button
 * methods, goto()/url()) and a `.spec.ts` smoke spec that exercises it.
 * The spec never talks to @apx/testkit directly for navigation/items — it
 * goes through the page object, so both artifacts stay in sync by
 * construction (see page-object.ts).
 *
 * Determinism contract: same export in -> byte-identical files out.
 * Pages are sorted by id; no timestamps; stable JSON ordering.
 */
import { readFileSync, readdirSync, mkdirSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { parseApp, type ApexPage } from '@apx/parser';
import {
  computeItemPropNames,
  pageObjectBaseName,
  pageObjectClassName,
  pageObjectFileName,
  pageObjectFor,
  specFileName,
} from './page-object.js';

export function loadExport(dir: string): Record<string, string> {
  const files: Record<string, string> = {};
  const addIf = (rel: string) => {
    try { files[rel] = readFileSync(join(dir, rel), 'utf8'); } catch { /* optional */ }
  };
  addIf('application.apx');
  addIf('page-groups.apx');
  for (const f of readdirSync(join(dir, 'pages')).sort()) {
    if (f.endsWith('.apx')) files[`pages/${f}`] = readFileSync(join(dir, 'pages', f), 'utf8');
  }
  return files;
}

const esc = (s: string) => s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");

function specFor(page: ApexPage): string {
  const isPublic = page.raw['security.authentication'] === 'public';
  const alias = page.alias ?? '';
  const path = alias.toLowerCase();
  const hidden = page.items.filter((i) => i.type === 'hidden');
  const visible = page.items.filter((i) => i.type !== 'hidden');
  const allItemIds = page.items.map((i) => `'${esc(i.identifier)}'`).join(', ');
  const firstText = visible.find((i) => i.type === 'textField' || i.type === 'textarea');
  const itemProp = firstText ? computeItemPropNames(page).get(firstText.identifier) : undefined;
  const className = pageObjectClassName(page);
  const poBase = pageObjectBaseName(page);

  const header = `/**
 * GENERATED by apx-testgen from pages/p${String(page.id).padStart(5, '0')}-${path}.apx — DO NOT EDIT.
 * Regenerate after any .apx change; review this file's diff alongside the .apx diff.
 * Assertions limited to runtime-verified contracts (V1-V5), implemented once in
 * @apx/testkit — see that package before touching any of the helpers used below.
 * Navigation and item access go through the generated page object
 * (./${poBase}.js), not raw testkit calls, so both stay in sync.
 * Regions present in metadata: ${page.regions.map((r) => r.identifier).join(', ') || '(none)'}
 * TODO(region-contract): emit region assertions once REGION DISCOVERY report
 * establishes the DOM convention for region static ids.
 */
import { expect, test } from '@playwright/test';
import { expectItemsPresent, normalizeTitle } from '@apx/testkit';
import { ${className} } from './${poBase}.js';
`;

  const describeOpen = isPublic
    ? `test.describe('page ${page.id}: ${esc(page.name ?? alias)}', () => {`
    : `// Page is not authentication:public — needs the login fixture (M2). Skipped until then.
test.describe.skip('page ${page.id}: ${esc(page.name ?? alias)} [requires auth]', () => {`;

  const bodyParts: string[] = [];

  bodyParts.push(`  test('loads via alias URL with clean console' , async ({ page }) => {
    const po = new ${className}(page);
    const errors = await po.goto();
    await page.waitForTimeout(1000);
    expect(errors).toEqual([]);
  });`);

  if (page.title) {
    bodyParts.push(`  test('title matches metadata (normalized)', async ({ page }) => {
    const po = new ${className}(page);
    await po.goto();
    expect(normalizeTitle(await page.title())).toBe(normalizeTitle('${esc(page.title)}'));
  });`);
  }

  if (page.items.length > 0) {
    bodyParts.push(`  test('every .apx pageItem exists in DOM/apex.item registry (${page.items.length} items, ${hidden.length} hidden)', async ({ page }) => {
    const po = new ${className}(page);
    await po.goto();
    await expectItemsPresent(page, [${allItemIds}]);
  });`);
  }

  if (firstText && itemProp) {
    bodyParts.push(`  test('apex.item round-trip on ${esc(firstText.identifier)}', async ({ page }) => {
    const po = new ${className}(page);
    await po.goto();
    await po.${itemProp}.setValue('apx-testgen');
    expect(await po.${itemProp}.getValue()).toBe('apx-testgen');
  });`);
  }

  return `${header}\n${describeOpen}\n${bodyParts.join('\n\n')}\n});\n`;
}

export interface GenerateResult {
  generated: number;
  skippedAuth: number;
  outDir: string;
  warnings: string[];
  unmodeled: string[];
  files: string[];
}

export function generate(exportDir: string, outDir: string): GenerateResult {
  const result = parseApp(loadExport(resolve(exportDir)));
  mkdirSync(resolve(outDir), { recursive: true });
  const pages = [...result.ast.pages].sort((a, b) => a.id - b.id).filter((p) => p.id !== 0 && p.alias);
  const files: string[] = [];
  for (const p of pages) {
    const poName = pageObjectFileName(p);
    writeFileSync(join(resolve(outDir), poName), pageObjectFor(p));
    files.push(poName);

    const specName = specFileName(p);
    writeFileSync(join(resolve(outDir), specName), specFor(p));
    files.push(specName);
  }
  return {
    generated: pages.length,
    skippedAuth: pages.filter((p) => p.raw['security.authentication'] !== 'public').length,
    outDir: resolve(outDir),
    warnings: result.warnings.map((w) => `${w.loc.file}:${w.loc.line} ${w.message}`),
    unmodeled: result.ast.unmodeled,
    files,
  };
}

export function inspect(exportDir: string) {
  const result = parseApp(loadExport(resolve(exportDir)));
  return {
    pages: result.ast.pages.map((p) => ({
      id: p.id, alias: p.alias, name: p.name,
      public: p.raw['security.authentication'] === 'public',
      regions: p.regions.map((r) => ({ id: r.identifier, type: r.type })),
      items: p.items.map((i) => ({ id: i.identifier, type: i.type, label: i.label })),
      buttons: p.buttons.map((b) => ({ id: b.identifier, label: b.label })),
    })),
    warnings: result.warnings.map((w) => `${w.loc.file}:${w.loc.line} ${w.message}`),
    unmodeled: result.ast.unmodeled,
  };
}
