/**
 * apx-testgen — deterministic Playwright smoke-spec generator for APEX 26.1+.
 *
 * Usage:  apx-testgen <export-dir> --out <tests-dir> [--base-url <url>]
 *
 * Emits ONLY assertions whose metadata->DOM contract has been VERIFIED on a
 * live 26.1 instance (see docs/grammar-assumptions.md "Runtime verification"):
 *   V1 friendly URL = lowercased page alias        (verified)
 *   V2 pageItem id -> DOM node id, verbatim        (verified)
 *   V3 apex.item(id) round-trip                    (verified)
 *   V4 title equality ONLY after NFKC+dash/space normalization (verified rule)
 *   V5 console-error guard                          (verified)
 * Region and button assertions are emitted as TODO comments until the
 * REGION/BUTTON DISCOVERY reports establish their DOM convention.
 *
 * Determinism contract: same export in -> byte-identical files out.
 * Pages are sorted by id; no timestamps; stable JSON ordering.
 */
import { readFileSync, readdirSync, mkdirSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { parseApp, type ApexPage } from '@apx/parser';

function loadExport(dir: string): Record<string, string> {
  const files: Record<string, string> = {};
  const addIf = (rel: string) => {
    try { files[rel] = readFileSync(join(dir, rel), 'utf8'); } catch { /* optional */ }
  };
  addIf('application.apx');
  addIf('page-groups.apx');
  for (const f of readdirSync(join(dir, 'pages')).sort()) {
    if (f.endsWith('.apx')) files[`pages/${f}`] = readFileSync(join(dir, 'pages', f), 'utf8');
  }
  return files;
}

const esc = (s: string) => s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");

function specFor(page: ApexPage): string {
  const isPublic = page.raw['security.authentication'] === 'public';
  const alias = page.alias ?? '';
  const path = alias.toLowerCase();
  const visible = page.items.filter((i) => i.type !== 'hidden');
  const hidden = page.items.filter((i) => i.type === 'hidden');
  const allItemIds = page.items.map((i) => `'${esc(i.identifier)}'`).join(', ');
  const firstText = visible.find((i) => i.type === 'textField' || i.type === 'textarea');

  const header = `/**
 * GENERATED by apx-testgen from pages/p${String(page.id).padStart(5, '0')}-${path}.apx — DO NOT EDIT.
 * Regenerate after any .apx change; review this file's diff alongside the .apx diff.
 * Assertions limited to runtime-verified contracts (V1-V5). Regions present in
 * metadata: ${page.regions.map((r) => r.identifier).join(', ') || '(none)'}
 * TODO(region-contract): emit region assertions once REGION DISCOVERY report
 * establishes the DOM convention for region static ids.
 */
import { expect, test, type Page } from '@playwright/test';
import { APP_BASE } from '../playwright.config.js';

const pageUrl = () => \`\${APP_BASE.replace(/\\/+$/, '')}/${esc(path)}\`;
const norm = (s: string) =>
  s.normalize('NFKC').replace(/[\\u2010-\\u2015\\u2212]/g, '-').replace(/[\\s\\u00A0]+/g, ' ').trim();

function armConsoleGuard(page: Page): string[] {
  const errors: string[] = [];
  page.on('console', (m) => { if (m.type() === 'error') errors.push(\`console.error: \${m.text()}\`); });
  page.on('pageerror', (e) => errors.push(\`pageerror: \${e.message}\`));
  return errors;
}

async function gotoPage(page: Page): Promise<string[]> {
  const errors = armConsoleGuard(page);
  const resp = await page.goto(pageUrl(), { waitUntil: 'domcontentloaded' });
  expect(resp?.ok(), \`GET \${pageUrl()} -> \${resp?.status()}\`).toBe(true);
  await page.waitForFunction(() => typeof (window as any).apex?.item === 'function');
  return errors;
}
`;

  const describeOpen = isPublic
    ? `test.describe('page ${page.id}: ${esc(page.name ?? alias)}', () => {`
    : `// Page is not authentication:public — needs the login fixture (M2). Skipped until then.
test.describe.skip('page ${page.id}: ${esc(page.name ?? alias)} [requires auth]', () => {`;

  const bodyParts: string[] = [];

  bodyParts.push(`  test('loads via alias URL with clean console' , async ({ page }) => {
    const errors = await gotoPage(page);
    await page.waitForTimeout(1000);
    expect(errors).toEqual([]);
  });`);

  if (page.title) {
    bodyParts.push(`  test('title matches metadata (normalized)', async ({ page }) => {
    await gotoPage(page);
    expect(norm(await page.title())).toBe(norm('${esc(page.title)}'));
  });`);
  }

  if (page.items.length > 0) {
    bodyParts.push(`  test('every .apx pageItem exists in DOM/apex.item registry (${page.items.length} items, ${hidden.length} hidden)', async ({ page }) => {
    await gotoPage(page);
    const presence = await page.evaluate(
      (ids: readonly string[]) =>
        ids.map((id) => ({
          id,
          ok: !!document.getElementById(id) || !!(window as any).apex.item(id)?.node,
        })),
      [${allItemIds}],
    );
    const missing = presence.filter((p) => !p.ok).map((p) => p.id);
    expect(missing, 'items declared in .apx but absent at runtime').toEqual([]);
  });`);
  }

  if (firstText) {
    bodyParts.push(`  test('apex.item round-trip on ${esc(firstText.identifier)}', async ({ page }) => {
    await gotoPage(page);
    const v = await page.evaluate(() => {
      const it = (window as any).apex.item('${esc(firstText.identifier)}');
      it.setValue('apx-testgen');
      return it.getValue();
    });
    expect(v).toBe('apx-testgen');
  });`);
  }

  return `${header}\n${describeOpen}\n${bodyParts.join('\n\n')}\n});\n`;
}


export interface GenerateResult {
  generated: number;
  skippedAuth: number;
  outDir: string;
  warnings: string[];
  unmodeled: string[];
  files: string[];
}

export function generate(exportDir: string, outDir: string): GenerateResult {
  const result = parseApp(loadExport(resolve(exportDir)));
  mkdirSync(resolve(outDir), { recursive: true });
  const pages = [...result.ast.pages].sort((a, b) => a.id - b.id).filter((p) => p.id !== 0 && p.alias);
  const files: string[] = [];
  for (const p of pages) {
    const name = `p${String(p.id).padStart(5, '0')}-${p.alias!.toLowerCase()}.spec.ts`;
    writeFileSync(join(resolve(outDir), name), specFor(p));
    files.push(name);
  }
  return {
    generated: files.length,
    skippedAuth: pages.filter((p) => p.raw['security.authentication'] !== 'public').length,
    outDir: resolve(outDir),
    warnings: result.warnings.map((w) => `${w.loc.file}:${w.loc.line} ${w.message}`),
    unmodeled: result.ast.unmodeled,
    files,
  };
}

export function inspect(exportDir: string) {
  const result = parseApp(loadExport(resolve(exportDir)));
  return {
    pages: result.ast.pages.map((p) => ({
      id: p.id, alias: p.alias, name: p.name,
      public: p.raw['security.authentication'] === 'public',
      regions: p.regions.map((r) => ({ id: r.identifier, type: r.type })),
      items: p.items.map((i) => ({ id: i.identifier, type: i.type, label: i.label })),
      buttons: p.buttons.map((b) => ({ id: b.identifier, label: b.label })),
    })),
    warnings: result.warnings.map((w) => `${w.loc.file}:${w.loc.line} ${w.message}`),
    unmodeled: result.ast.unmodeled,
  };
}
