/**
 * apx-testgen — deterministic Playwright page-object + smoke-spec generator
 * for APEX 26.1+.
 *
 * Usage:  apx-testgen <export-dir> --out <tests-dir>
 * (base URL is read by the generated code from the consuming project's own
 * playwright.config.ts — APP_BASE export — not a generator flag; see
 * spike/playwright.config.ts for the convention generated imports assume.)
 *
 * Emits ONLY assertions whose metadata->DOM contract has been VERIFIED on a
 * live 26.1 instance (see docs/grammar-assumptions.md "Runtime verification"):
 *   V1 friendly URL = lowercased page alias        (verified)
 *   V2 pageItem id -> DOM node id, verbatim        (verified)
 *   V3 apex.item(id) round-trip                    (verified)
 *   V4 title equality ONLY after NFKC+dash/space normalization (verified rule)
 *   V5 console-error guard                          (verified)
 *   V6 labeled button exists (accessible-role locator, subsumed by the
 *      stronger clickability requirement generated click methods already
 *      exercise live -- see button.ts)              (verified)
 * Region assertions are NOT yet emitted here -- the region-identifier-to-
 * DOM convention is still an open ledger item for most region types (see
 * docs/grammar-assumptions.md "Still open"); ADR-003 in .ai/ADR/ covers
 * the specific, narrower cases (Chart/Interactive Grid via htmlDomId)
 * where a runtime id IS predictable.
 * V1-V6 are implemented once in @apx/testkit and imported by generated
 * code (never duplicated) — see packages/testkit for the primitives.
 *
 * Two files per page: a `.page.ts` PageObject (typed item accessors, button
 * methods, goto()/url()) and a `.spec.ts` smoke spec that exercises it.
 * The spec never talks to @apx/testkit directly for navigation/items — it
 * goes through the page object, so both artifacts stay in sync by
 * construction (see page-object.ts).
 *
 * Determinism contract: same export in -> byte-identical files out.
 * Pages are sorted by id; no timestamps; stable JSON ordering.
 */
import { readFileSync, readdirSync, mkdirSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { parseApp, type ApexPage } from '@apx/parser';
import {
  computeItemPropNames,
  pageObjectBaseName,
  pageObjectClassName,
  pageObjectFileName,
  pageObjectFor,
  specFileName,
} from './page-object.js';

export function loadExport(dir: string): Record<string, string> {
  const files: Record<string, string> = {};
  const addIf = (rel: string) => {
    try { files[rel] = readFileSync(join(dir, rel), 'utf8'); } catch { /* optional */ }
  };
  addIf('application.apx');
  addIf('page-groups.apx');
  for (const f of readdirSync(join(dir, 'pages')).sort()) {
    if (f.endsWith('.apx')) files[`pages/${f}`] = readFileSync(join(dir, 'pages', f), 'utf8');
  }
  return files;
}

const esc = (s: string) => s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");

/**
 * Region types confirmed live to resolve as `apex.region()` widget
 * regions (ADR-003) -- `form`/`staticContent` are confirmed NOT to
 * resolve at all, by design, and every other type either has no runtime
 * wrapper yet or needs Chart/IG's additional widget-container suffix
 * (out of scope for this generic "region resolves" assertion).
 */
const RESOLVABLE_REGION_TYPES = new Set(['interactiveReport', 'cards', 'facetedSearch']);

/**
 * ADR-003 layered resolution: htmlDomId (when set) IS the runtime id,
 * verbatim, for ANY region type -- not just Chart/Interactive Grid.
 * Falls back to the .apx export identifier otherwise (true for the
 * large majority of regions, but not a guarantee -- see the ADR).
 */
function resolvedRegionId(region: { identifier: string; htmlDomId: string | null }): string {
  return region.htmlDomId ?? region.identifier;
}

function specFor(page: ApexPage): string {
  const isPublic = page.raw['security.authentication'] === 'public';
  const alias = page.alias ?? '';
  const path = alias.toLowerCase();
  const hidden = page.items.filter((i) => i.type === 'hidden');
  const visible = page.items.filter((i) => i.type !== 'hidden');
  const allItemIds = page.items.map((i) => `'${esc(i.identifier)}'`).join(', ');
  const labeledButtons = page.buttons.filter((b) => b.label);
  const allButtonLabels = labeledButtons.map((b) => `'${esc(b.label!)}'`).join(', ');
  const resolvableRegions = page.regions.filter((r) => r.type && RESOLVABLE_REGION_TYPES.has(r.type));
  const skippedRegions = page.regions.filter((r) => !r.type || !RESOLVABLE_REGION_TYPES.has(r.type));
  const resolvableRegionIds = resolvableRegions.map((r) => `'${esc(resolvedRegionId(r))}'`).join(', ');
  const firstText = visible.find((i) => i.type === 'textField' || i.type === 'textarea');
  const itemProp = firstText ? computeItemPropNames(page).get(firstText.identifier) : undefined;
  const className = pageObjectClassName(page);
  const poBase = pageObjectBaseName(page);

  const header = `/**
 * GENERATED by apx-testgen from pages/p${String(page.id).padStart(5, '0')}-${path}.apx — DO NOT EDIT.
 * Regenerate after any .apx change; review this file's diff alongside the .apx diff.
 * Assertions limited to runtime-verified contracts (V1-V6), implemented once in
 * @apx/testkit — see that package before touching any of the helpers used below.
 * Navigation and item access go through the generated page object
 * (./${poBase}.js), not raw testkit calls, so both stay in sync.
 * Regions present in metadata: ${page.regions.map((r) => r.identifier).join(', ') || '(none)'}
 * ${resolvableRegions.length > 0
     ? `Region resolve-check emitted for ${resolvableRegions.length} interactiveReport/cards/facetedSearch region(s) below (ADR-003 htmlDomId-resolved where set).`
     : 'No interactiveReport/cards/facetedSearch regions on this page -- no region resolve-check to emit.'}
 * ${skippedRegions.length > 0
     ? `Region types NOT covered by an auto-generated assertion (no verified DOM convention, or a runtime id genuinely unconstructible from static data -- see docs/grammar-assumptions.md "Still open" and ADR-003): ${skippedRegions.map((r) => `${r.identifier} (${r.type ?? 'untyped'})`).join(', ')}.`
     : ''}${isPublic ? '' : `
 * This page is not authentication:public. Tests log in via @apx/testkit's
 * login() in a beforeEach, gated on APX_LOGIN_TEST_USERNAME/
 * APX_LOGIN_TEST_PASSWORD -- skips cleanly at runtime if either is unset,
 * rather than being permanently skipped at file-load time. login() assumes
 * this app's DEFAULT APEX authentication scheme, with a standard
 * P101_USERNAME/P101_PASSWORD login page reachable at <app-base>/login
 * (confirmed live against a real APEX app -- see
 * spike/tests/auth-login-verify.spec.ts). Apps using a CUSTOM
 * authentication scheme will get a clear, specific error straight from
 * login() itself (e.g. "P101_USERNAME not found") instead of a silent
 * hang -- that is the correct, intended failure mode for those apps, not a
 * bug to work around here.`}
 */
import { expect, test } from '@playwright/test';
import { expectItemsPresent${labeledButtons.length > 0 ? ', expectButtonsPresent' : ''}${resolvableRegions.length > 0 ? ', expectRegionsResolve' : ''}, normalizeTitle${isPublic ? '' : ', login'} } from '@apx/testkit';
import { ${className} } from './${poBase}.js';${isPublic ? '' : `
import { APP_BASE } from '../playwright.config.js';`}
`;

  const describeOpen = isPublic
    ? `test.describe('page ${page.id}: ${esc(page.name ?? alias)}', () => {`
    : `test.describe('page ${page.id}: ${esc(page.name ?? alias)} [requires auth]', () => {
  test.beforeEach(async ({ page }) => {
    const username = process.env.APX_LOGIN_TEST_USERNAME;
    const password = process.env.APX_LOGIN_TEST_PASSWORD;
    test.skip(
      !username || !password,
      'Set APX_LOGIN_TEST_USERNAME and APX_LOGIN_TEST_PASSWORD to run tests against this authenticated page.',
    );
    await page.goto(\`\${APP_BASE}/login\`, { waitUntil: 'domcontentloaded' });
    await login(page, { username: username!, password: password! });
  });`;

  const bodyParts: string[] = [];

  bodyParts.push(`  test('loads via alias URL with clean console' , async ({ page }) => {
    const po = new ${className}(page);
    const errors = await po.goto();
    await page.waitForTimeout(1000);
    expect(errors).toEqual([]);
  });`);

  if (page.title) {
    bodyParts.push(`  test('title matches metadata (normalized)', async ({ page }) => {
    const po = new ${className}(page);
    await po.goto();
    expect(normalizeTitle(await page.title())).toBe(normalizeTitle('${esc(page.title)}'));
  });`);
  }

  if (page.items.length > 0) {
    bodyParts.push(`  test('every .apx pageItem exists in DOM/apex.item registry (${page.items.length} items, ${hidden.length} hidden)', async ({ page }) => {
    const po = new ${className}(page);
    await po.goto();
    await expectItemsPresent(page, [${allItemIds}]);
  });`);
  }

  if (firstText && itemProp) {
    bodyParts.push(`  test('apex.item round-trip on ${esc(firstText.identifier)}', async ({ page }) => {
    const po = new ${className}(page);
    await po.goto();
    await po.${itemProp}.setValue('apx-testgen');
    expect(await po.${itemProp}.getValue()).toBe('apx-testgen');
  });`);
  }

  if (labeledButtons.length > 0) {
    bodyParts.push(`  test('every labeled .apx button exists (${labeledButtons.length} button${labeledButtons.length === 1 ? '' : 's'})', async ({ page }) => {
    const po = new ${className}(page);
    await po.goto();
    await expectButtonsPresent(page, [${allButtonLabels}]);
  });`);
  }

  if (resolvableRegions.length > 0) {
    bodyParts.push(`  test('every interactiveReport/cards/facetedSearch region resolves (${resolvableRegions.length} region${resolvableRegions.length === 1 ? '' : 's'})', async ({ page }) => {
    const po = new ${className}(page);
    await po.goto();
    await expectRegionsResolve(page, [${resolvableRegionIds}]);
  });`);
  }

  return `${header}\n${describeOpen}\n${bodyParts.join('\n\n')}\n});\n`;
}

export interface GenerateResult {
  generated: number;
  skippedAuth: number;
  outDir: string;
  warnings: string[];
  unmodeled: string[];
  files: string[];
}

export function generate(exportDir: string, outDir: string): GenerateResult {
  const result = parseApp(loadExport(resolve(exportDir)));
  mkdirSync(resolve(outDir), { recursive: true });
  const pages = [...result.ast.pages].sort((a, b) => a.id - b.id).filter((p) => p.id !== 0 && p.alias);
  const files: string[] = [];
  for (const p of pages) {
    const poName = pageObjectFileName(p);
    writeFileSync(join(resolve(outDir), poName), pageObjectFor(p));
    files.push(poName);

    const specName = specFileName(p);
    writeFileSync(join(resolve(outDir), specName), specFor(p));
    files.push(specName);
  }
  return {
    generated: pages.length,
    skippedAuth: pages.filter((p) => p.raw['security.authentication'] !== 'public').length,
    outDir: resolve(outDir),
    warnings: result.warnings.map((w) => `${w.loc.file}:${w.loc.line} ${w.message}`),
    unmodeled: result.ast.unmodeled,
    files,
  };
}

export function inspect(exportDir: string) {
  const result = parseApp(loadExport(resolve(exportDir)));
  return {
    pages: result.ast.pages.map((p) => ({
      id: p.id, alias: p.alias, name: p.name,
      public: p.raw['security.authentication'] === 'public',
      regions: p.regions.map((r) => ({ id: r.identifier, type: r.type })),
      items: p.items.map((i) => ({ id: i.identifier, type: i.type, label: i.label })),
      buttons: p.buttons.map((b) => ({ id: b.identifier, label: b.label })),
    })),
    warnings: result.warnings.map((w) => `${w.loc.file}:${w.loc.line} ${w.message}`),
    unmodeled: result.ast.unmodeled,
  };
}
