import { createHash, randomUUID } from 'node:crypto';
import { existsSync, lstatSync, mkdirSync, mkdtempSync, readFileSync, renameSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { generate } from './lib.js';

const MANIFEST = '.apx-testgen-manifest.json';
const LOCK = '.apx-testgen.lock';
const BACKUPS = '.apx-testgen-backups';
type Ownership = { version: 1; files: Record<string, string> };
export interface RegenerationPlan {
  version: 1;
  outDir: string;
  planHash: string;
  changes: { file: string; action: 'create' | 'update' | 'retire' | 'unchanged' | 'conflict'; reason: string }[];
  conflicts: string[];
}
const hash = (data: string | Buffer) => createHash('sha256').update(data).digest('hex');
const validFile = (name: string) => /^p\d+-[^/\\]+\.(page|spec)\.ts$/.test(name) && !/[\x00-\x1f]/.test(name);

function regularFile(path: string): Buffer | null {
  let stat;
  try { stat = lstatSync(path); } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return null;
    throw error;
  }
  if (!stat.isFile() || stat.isSymbolicLink()) throw new Error(`Refusing non-regular output file: ${path}`);
  return readFileSync(path);
}
function directory(path: string): void {
  if (!existsSync(path)) {
    // existsSync follows symlinks; explicitly reject dangling links too.
    try { lstatSync(path); } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') return;
      throw error;
    }
    throw new Error(`Refusing output symlink: ${path}`);
  }
  const stat = lstatSync(path);
  if (!stat.isDirectory() || stat.isSymbolicLink()) throw new Error(`Expected a non-symlink output directory: ${path}`);
}
function ownership(bytes: Buffer | null): Ownership {
  if (!bytes) return { version: 1, files: {} };
  const value = JSON.parse(bytes.toString('utf8')) as Ownership;
  if (!value || value.version !== 1 || Object.keys(value).some(key => !['version', 'files'].includes(key)) || !value.files || typeof value.files !== 'object' || Array.isArray(value.files)) throw new Error('Invalid generation ownership manifest');
  for (const [file, digest] of Object.entries(value.files)) {
    if (!validFile(file) || typeof digest !== 'string' || !/^[a-f0-9]{64}$/.test(digest)) throw new Error('Invalid generation ownership entry');
  }
  return value;
}
function prepare(exportDir: string, outDir: string) {
  const output = resolve(outDir);
  directory(output);
  const manifestBytes = regularFile(join(output, MANIFEST));
  const owned = ownership(manifestBytes);
  const staging = mkdtempSync(join(tmpdir(), 'apx-regenerate-'));
  const desired = new Map<string, Buffer>();
  try {
    const generated = generate(exportDir, staging);
    for (const file of generated.files.sort()) {
      if (!validFile(file) || desired.has(file)) throw new Error(`Unsafe or duplicate generated filename: ${file}`);
      desired.set(file, readFileSync(join(staging, file)));
    }
  } finally { rmSync(staging, { recursive: true, force: true }); }
  const changes: RegenerationPlan['changes'] = [];
  const conflicts: string[] = [];
  const state: [string, string | null, string | null][] = [];
  for (const file of [...new Set([...Object.keys(owned.files), ...desired.keys()])].sort()) {
    const existing = regularFile(join(output, file));
    const next = desired.get(file);
    state.push([file, existing ? hash(existing) : null, next ? hash(next) : null]);
    let action: RegenerationPlan['changes'][number]['action'];
    let reason: string;
    if (existing && !Object.hasOwn(owned.files, file)) {
      action = 'conflict'; reason = 'Existing file is not owned by safe regeneration.';
    } else if (existing && hash(existing) !== owned.files[file]) {
      action = 'conflict'; reason = 'Owned file was edited after generation.';
    } else if (!existing && Object.hasOwn(owned.files, file)) {
      action = 'conflict'; reason = 'Owned file was removed after generation.';
    } else if (!next) {
      action = 'retire'; reason = 'No longer generated; move the owned file to backup.';
    } else if (!existing) {
      action = 'create'; reason = 'New generated file.';
    } else if (hash(existing) === hash(next)) {
      action = 'unchanged'; reason = 'Owned generated bytes are unchanged.';
    } else {
      action = 'update'; reason = 'Replace unchanged owned file, keeping a backup.';
    }
    changes.push({ file, action, reason });
    if (action === 'conflict') conflicts.push(file);
  }
  const plan: RegenerationPlan = {
    version: 1, outDir: output,
    planHash: `sha256:${hash(JSON.stringify({ output, manifest: manifestBytes?.toString('base64') ?? null, state }))}`,
    changes, conflicts,
  };
  return { plan, desired, manifestBytes };
}

/** Preview without modifying the destination. Temporary rendering is discarded. */
export function previewRegeneration(exportDir: string, outDir: string): RegenerationPlan {
  return prepare(exportDir, outDir).plan;
}

/** Apply exactly a previously previewed plan. No force-overwrite mode. */
export function applyRegeneration(exportDir: string, outDir: string, expectedPlanHash: string): { plan: RegenerationPlan; backupDir: string | null } {
  const prepared = prepare(exportDir, outDir);
  if (prepared.plan.planHash !== expectedPlanHash) throw new Error('Regeneration plan changed; preview again before applying.');
  if (prepared.plan.conflicts.length) throw new Error(`Regeneration blocked by conflicts: ${prepared.plan.conflicts.join(', ')}`);
  const output = prepared.plan.outDir;
  mkdirSync(output, { recursive: true });
  // Cooperative exclusion: other writers must keep the destination idle.
  const lock = join(output, LOCK);
  writeFileSync(lock, expectedPlanHash, { flag: 'wx' });
  let backupDir: string | null = null;
  try {
    const fresh = prepare(exportDir, outDir);
    if (fresh.plan.planHash !== expectedPlanHash) throw new Error('Output or generated content changed while acquiring the lock; preview again.');
    const operations = fresh.plan.changes.filter(change => change.action !== 'unchanged');
    if (operations.length || !fresh.manifestBytes) {
      directory(join(output, BACKUPS));
      mkdirSync(join(output, BACKUPS), { recursive: true });
      backupDir = join(output, BACKUPS, randomUUID());
      mkdirSync(backupDir);
      // Save the old manifest and every displaced file before overwriting.
      if (fresh.manifestBytes) renameSync(join(output, MANIFEST), join(backupDir, MANIFEST));
      for (const change of operations) {
        const target = join(output, change.file);
        if (change.action === 'update' || change.action === 'retire') renameSync(target, join(backupDir, change.file));
        if (change.action === 'create' || change.action === 'update') writeFileSync(target, fresh.desired.get(change.file)!, { flag: 'wx' });
      }
      const nextManifest: Ownership = { version: 1, files: Object.fromEntries([...fresh.desired].map(([file, bytes]) => [file, hash(bytes)])) };
      writeFileSync(join(output, MANIFEST), JSON.stringify(nextManifest, null, 2) + '\n', { flag: 'wx' });
    }
    return { plan: fresh.plan, backupDir };
  } catch (error) {
    throw new Error(`${error instanceof Error ? error.message : String(error)}${backupDir ? ` Recovery backup: ${backupDir}. Stop and restore before retrying.` : ''}`);
  } finally { rmSync(lock); }
}
