/**
 * GENERATED by apx-testgen from pages/p00030-quick-edit-drawer.apx — DO NOT EDIT.
 * Typed accessor page object built on @apx/testkit primitives — no raw
 * selectors. Item accessors rest on the VERIFIED apex.item contract; button
 * methods use accessible-role/label locators (region/button DOM convention
 * still open — see docs/grammar-assumptions.md). Click methods pass their
 * button's semantic identity (pageId + .apx identifier) through to
 * clickButton() so coverage tracking never collapses two different,
 * same-labeled buttons into one entry -- see @apx/testkit's coverage.ts.
 * Buttons whose label collides with another button's on this same page do
 * NOT get a generated click method at all -- see the comment in their
 * place below for why and what would resolve it.
 */
import type { Page } from '@playwright/test';
import { ApexItem, apexPageUrl, clickButton, gotoApexPage } from '@apx/testkit';
import { APP_BASE } from '../playwright.config.js';

export class QuickEditDrawerPage {
  static readonly alias = 'quick-edit-drawer';

  constructor(private readonly page: Page) {}

  url(): string {
    return apexPageUrl(APP_BASE, QuickEditDrawerPage.alias);
  }

  /** Navigate here and arm the console guard; returns any console/page errors seen. */
  async goto(): Promise<string[]> {
    return gotoApexPage(this.page, this.url());
  }

  /** hidden */
  get noteId(): ApexItem {
    return new ApexItem(this.page, 'P30_NOTE_ID', 30);
  }

  /** textarea, "Note" */
  get noteText(): ApexItem {
    return new ApexItem(this.page, 'P30_NOTE_TEXT', 30);
  }

  /** "Save" */
  async clickSaveNote(): Promise<void> {
    await clickButton(this.page, 'Save', { pageId: 30, identifier: 'save_note' });
  }
}
