/**
 * GENERATED by apx-testgen from pages/p00030-quick-edit-drawer.apx — DO NOT EDIT.
 * Regenerate after any .apx change; review this file's diff alongside the .apx diff.
 * Assertions limited to runtime-verified contracts (V1-V6), implemented once in
 * @apx/testkit — see that package before touching any of the helpers used below.
 * Navigation and item access go through the generated page object
 * (./p00030-quick-edit-drawer.page.js), not raw testkit calls, so both stay in sync.
 * Regions present in metadata: quick-edit-form
 * No interactiveReport/cards/facetedSearch regions on this page -- no region resolve-check to emit.
 * Other region types NOT covered by an auto-generated assertion (no verified DOM convention -- see docs/grammar-assumptions.md "Still open"): quick-edit-form (form).
 * NOT AUTO-ROUTABLE (modalDialog): this page declares appearance.pageMode: modalDialog -- confirmed live that a plain GET returns HTTP 400 instead of loading (docs/quirks/26.1.json 'drawer-modal-pages-400'). Every test below is unconditionally skipped rather than generated to guaranteed-fail.
 */
import { expect, test } from '@playwright/test';
import { expectItemsPresent, expectButtonsPresent, normalizeTitle } from '@apx/testkit';
import { QuickEditDrawerPage } from './p00030-quick-edit-drawer.page.js';

test.describe('page 30: Quick Edit Drawer [not auto-routable -- skipped]', () => {
  test.beforeEach(async () => {
    // apx-testkit: this page cannot be safely reached by a normal
    // generated test -- see this file's header comment (NOT
    // AUTO-ROUTABLE lines) for the specific reason(s). Every test below
    // is unconditionally skipped rather than generated to
    // guaranteed-fail.
    test.skip(
      true,
      'apx-testkit: modalDialog requires parent-page navigation (a plain GET to this page returns HTTP 400) -- see docs/quirks/26.1.json drawer-modal-pages-400.',
    );
  });
  test('loads via alias URL with clean console' , async ({ page }) => {
    const po = new QuickEditDrawerPage(page);
    const errors = await po.goto();
    await page.waitForTimeout(1000);
    expect(errors).toEqual([]);
  });

  test('title matches metadata (normalized)', async ({ page }) => {
    const po = new QuickEditDrawerPage(page);
    await po.goto();
    expect(normalizeTitle(await page.title())).toBe(normalizeTitle('Quick Edit Drawer'));
  });

  test('every .apx pageItem exists in DOM/apex.item registry (2 items, 1 hidden)', async ({ page }) => {
    const po = new QuickEditDrawerPage(page);
    await po.goto();
    await expectItemsPresent(page, ['P30_NOTE_ID', 'P30_NOTE_TEXT'], 30);
  });

  test('apex.item round-trip on P30_NOTE_TEXT', async ({ page }) => {
    const po = new QuickEditDrawerPage(page);
    await po.goto();
    await po.noteText.setValue('apx-testgen');
    expect(await po.noteText.getValue()).toBe('apx-testgen');
  });

  test('every uniquely labeled .apx button exists (1 button)', async ({ page }) => {
    const po = new QuickEditDrawerPage(page);
    await po.goto();
    await expectButtonsPresent(page, ['Save'], [{ pageId: 30, identifier: 'save_note' }]);
  });
});
