/**
 * GENERATED by apx-testgen from pages/p00070-browse-catalog.apx — DO NOT EDIT.
 * Regenerate after any .apx change; review this file's diff alongside the .apx diff.
 * Assertions limited to runtime-verified contracts (V1-V6), implemented once in
 * @apx/testkit — see that package before touching any of the helpers used below.
 * Navigation and item access go through the generated page object
 * (./p00070-browse-catalog.page.js), not raw testkit calls, so both stay in sync.
 * Regions present in metadata: active-facets, catalog-cards
 * Region resolve-check emitted for 2 interactiveReport/cards/facetedSearch region(s) below -- resolved LIVE via resolveRegion() (ADR-003: htmlDomId tried first when set, then the export identifier), never a static id baked in at generation time.
 */
import { expect, test } from '@playwright/test';
import { resolveRegion, normalizeTitle } from '@apx/testkit';
import { BrowseCatalogPage } from './p00070-browse-catalog.page.js';

test.describe('page 70: Browse Catalog', () => {
  test('loads via alias URL with clean console' , async ({ page }) => {
    const po = new BrowseCatalogPage(page);
    const errors = await po.goto();
    await page.waitForTimeout(1000);
    expect(errors).toEqual([]);
  });

  test('title matches metadata (normalized)', async ({ page }) => {
    const po = new BrowseCatalogPage(page);
    await po.goto();
    expect(normalizeTitle(await page.title())).toBe(normalizeTitle('Browse Catalog'));
  });

  test('every interactiveReport/cards/facetedSearch region resolves (2 regions)', async ({ page }) => {
    const po = new BrowseCatalogPage(page);
    await po.goto();
    // ADR-003 layered resolution, confirmed LIVE per region (htmlDomId
    // tried first when set, then the export identifier) -- resolveRegion()
    // hard-fails with a specific message if neither candidate resolves,
    // rather than silently trusting a static guess.
    const regionCandidateSets = [
      [{ value: 'active-facets', strategy: 'export-identifier' as const }],
      [{ value: 'catalog-cards', strategy: 'export-identifier' as const }]
    ];
    for (const candidates of regionCandidateSets) {
      await resolveRegion(page, candidates);
    }
  });
});
