/**
 * GENERATED by apx-testgen from pages/p00020-my-account.apx — DO NOT EDIT.
 * Typed accessor page object built on @apx/testkit primitives — no raw
 * selectors. Item accessors rest on the VERIFIED apex.item contract; button
 * methods use accessible-role/label locators (region/button DOM convention
 * still open — see docs/grammar-assumptions.md). Click methods pass their
 * button's semantic identity (pageId + .apx identifier) through to
 * buttonByLabel() so coverage tracking never collapses two different,
 * same-labeled buttons into one entry -- see @apx/testkit's coverage.ts.
 * Buttons whose label collides with another button's on this same page do
 * NOT get a generated click method at all -- see the comment in their
 * place below for why and what would resolve it.
 */
import type { Page } from '@playwright/test';
import { ApexItem, apexPageUrl, buttonByLabel, gotoApexPage } from '@apx/testkit';
import { APP_BASE } from '../playwright.config.js';

export class MyAccountPage {
  static readonly alias = 'my-account';

  constructor(private readonly page: Page) {}

  url(): string {
    return apexPageUrl(APP_BASE, MyAccountPage.alias);
  }

  /** Navigate here and arm the console guard; returns any console/page errors seen. */
  async goto(): Promise<string[]> {
    return gotoApexPage(this.page, this.url());
  }

  /** hidden */
  get accountId(): ApexItem {
    return new ApexItem(this.page, 'P20_ACCOUNT_ID');
  }

  /** textField, "Display Name" */
  get displayName(): ApexItem {
    return new ApexItem(this.page, 'P20_DISPLAY_NAME');
  }

  /** "Save" */
  async clickSaveAccount(): Promise<void> {
    await buttonByLabel(this.page, 'Save', { pageId: 20, identifier: 'save_account' }).click();
  }
}
