/**
 * GENERATED by apx-testgen from pages/p00090-employee-grid.apx — DO NOT EDIT.
 * Regenerate after any .apx change; review this file's diff alongside the .apx diff.
 * Assertions limited to runtime-verified contracts (V1-V6), implemented once in
 * @apx/testkit — see that package before touching any of the helpers used below.
 * Navigation and item access go through the generated page object
 * (./p00090-employee-grid.page.js), not raw testkit calls, so both stay in sync.
 * Regions present in metadata: employee-editing, department-editing
 * No interactiveReport/cards/facetedSearch regions on this page -- no region resolve-check to emit.
 * Interactive Grid view-check emitted for 1 region(s) with a known runtime id (htmlDomId set), resolved live via resolveRegion() before use.
 * 1 Interactive Grid region(s) SKIPPED -- no htmlDomId set, runtime id genuinely unconstructible from static data (ADR-003 layer 3): department-editing.
 * NOT AUTO-ROUTABLE (navigation unsafe): this page declares security.pageAccessProtection: argumentsMustHaveChecksum and is NOT authentication:public -- a bare page.goto() is confirmed to redirect an authenticated session to /login (docs/quirks/26.1.json 'page-access-protection-blocks-bare-navigation'). Every test below is unconditionally skipped rather than generated to guaranteed-fail; see @apx/testkit's navigateViaUiPath() for the confirmed-working alternative (not auto-derivable here without Flow Map wiring).
 */
import { expect, test } from '@playwright/test';
import { resolveRegion, ApexInteractiveGridRegion, normalizeTitle } from '@apx/testkit';
import { EmployeeGridPage } from './p00090-employee-grid.page.js';

test.describe('page 90: Employee Grid [not auto-routable -- skipped]', () => {
  test.beforeEach(async () => {
    // apx-testkit: this page cannot be safely reached by a normal
    // generated test -- see this file's header comment (NOT
    // AUTO-ROUTABLE lines) for the specific reason(s). Every test below
    // is unconditionally skipped rather than generated to
    // guaranteed-fail.
    test.skip(
      true,
      'apx-testkit: navigation unsafe (security.pageAccessProtection: argumentsMustHaveChecksum on a non-public page) -- a bare page.goto() is confirmed to redirect an authenticated session to /login. See @apx/testkit\'s navigateViaUiPath() for the confirmed-working alternative, and docs/quirks/26.1.json page-access-protection-blocks-bare-navigation.',
    );
  });
  test('loads via alias URL with clean console' , async ({ page }) => {
    const po = new EmployeeGridPage(page);
    const errors = await po.goto();
    await page.waitForTimeout(1000);
    expect(errors).toEqual([]);
  });

  test('title matches metadata (normalized)', async ({ page }) => {
    const po = new EmployeeGridPage(page);
    await po.goto();
    expect(normalizeTitle(await page.title())).toBe(normalizeTitle('Employee Grid'));
  });

  test('every Interactive Grid region with a known runtime id resolves a current view (1 region)', async ({ page }) => {
    const po = new EmployeeGridPage(page);
    await po.goto();
    // ADR-003: htmlDomId is the ONLY evidence-backed candidate for
    // Interactive Grid -- the export identifier is confirmed NOT to work
    // as a fallback for this component type (e.g. 'basic-editing'
    // resolves to null; only 'emp', the htmlDomId value, resolves).
    const regionCandidateSets = [
      [{ value: 'emp', strategy: 'htmlDomId' as const }]
    ];
    for (const candidates of regionCandidateSets) {
      const { runtimeId } = await resolveRegion(page, candidates, 90);
      const ig = new ApexInteractiveGridRegion(page, runtimeId, 90);
      expect(typeof await ig.getCurrentViewId()).toBe('string');
    }
  });
});
